import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const PPEditorialOld = localFont({
  src: "./fonts/PPEditorialOld-Italic.woff",
  variable: "--font-pp-editorial-old",
  weight: "400",
});

const BlurWeb = localFont({
  src: "./fonts/BlurWeb-Medium.otf",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PPEditorialOld.variable} ${BlurWeb.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
